# Generated by Django 4.2.5 on 2023-09-09 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calenders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('today_complete', models.BooleanField()),
                ('workouts', models.ManyToManyField(related_name='calenders', to='workouts.workout')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
