# Generated by Django 4.2.5 on 2023-09-11 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calenders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calender',
            name='users',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calenders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='calender',
            name='workouts',
            field=models.ManyToManyField(related_name='calenders', to='workouts.workout'),
        ),
    ]
