# Generated by Django 4.2.5 on 2023-09-11 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('workoutmethod', models.CharField(choices=[('body_weight', '맨몸 운동'), ('free_weight', '프리웨이트'), ('machines', '머신 운동')], default='body_weight', max_length=15)),
                ('classification', models.CharField(choices=[('bust', '상반신'), ('lower_body', '하반신'), ('chest', '가슴'), ('back', '등'), ('thigh', '허벅지'), ('shoulder', '어깨'), ('arm', '팔'), ('core', '코어'), ('calf', '종아리')], default='bust', max_length=15)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
