# Generated by Django 4.2.5 on 2023-09-09 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_remove_workout_today_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='classification',
            field=models.CharField(choices=[('bust', '상반신'), ('lower_body', '하반신'), ('chest', '가슴'), ('back', '등'), ('thigh', '허벅지'), ('shoulder', '어깨'), ('arm', '팔'), ('core', '코어'), ('calf', '종아리')], default='bust', max_length=15),
        ),
        migrations.AddField(
            model_name='workout',
            name='workoutmethod',
            field=models.CharField(choices=[('body_weight', '맨몸 운동'), ('free_weight', '프리웨이트'), ('machines', '머신 운동')], default='body_weight', max_length=15),
        ),
    ]
